apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: mgmt-argo-rt-443
  namespace: argocd
spec:
  hosts:
  - '*'
  http:
  - name: argocd
    labels:
      waf: "true"
    matchers:
    - uri:
        prefix: /argo
    forwardTo:
      destinations:
      - port:
          number: 443
        ref:
          cluster: mgmt
          name: argocd-server
          namespace: argocd
  virtualGateways:
  - cluster: mgmt
    name: north-south-gw
    namespace: istio-gateways
  workloadSelectors: []