apiVersion: v1
kind: ServiceAccount
metadata:
  name: podinfo
  namespace: podinfo
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo
  labels:
    app: podinfo
    service: podinfo
spec:
  ports:
  - name: http
    port: 9898
    targetPort: 9898
  selector:
    app: podinfo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: istio-success-rate
  namespace: podinfo
spec:
  args:
  - name: service
  - name: namespace
  metrics:
  - initialDelay: 30s
    interval: 20s
    name: success-rate
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: >+
          sum(irate(istio_requests_total{
            reporter="source",
            destination_service=~"{{args.service}}.{{args.namespace}}.svc.cluster.local",
            response_code!~"5.*"}[40s])
          )
          /
          sum(irate(istio_requests_total{
            reporter="source",
            destination_service=~"{{args.service}}.{{args.namespace}}.svc.cluster.local"}[40s])
          )
    successCondition: result[0] > 0.95
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: podinfo
  namespace: podinfo
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: podinfo
  strategy:
    canary:
      ###########################
      # uncomment below to add steps
      steps:
      - setWeight: 10
      - pause: {duration: 20}
      - setWeight: 80
      - pause: {duration: 20}
      ###########################
      # uncomment below to use AnalysisTemplate
      analysis:
        args:
        - name: service
          value: podinfo
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        startingStep: 1
        templates:
        - templateName: istio-success-rate
      ###########################
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: version-canary
            name: podinfo-podinfo-svc-cluster-loc-bc96aa96c8984be2c6fa0d59a031dbe
            stableSubsetName: version-stable
          virtualService:
            name: routetable-podinfo-rt-443-podinfo-mgmt-ops-team.istio-gateways
            routes:
            - podinfo-podinfo-rt-443.podinfo.mgmt
  template:
    metadata:
      labels:
        app: podinfo
        version: stable
    spec:
      containers:
      - name: podinfod
        image: ghcr.io/stefanprodan/podinfo:6.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: rollout-destrule
  namespace: podinfo
spec:
  host: podinfo
  subsets:
  - labels:
      app: podinfo
    name: version-stable
  - labels:
      app: podinfo
    name: version-canary
