apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge-enterprise-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-ee
    helm:
      skipCrds: false
      values: |
        create_license_secret: false
        gloo:
          license_secret_name: license
          gatewayProxies:
            gatewayProxy:
              podTemplate:
                # graceful shutdown: Envoy will fail health checks but only stop after 7 seconds
                terminationGracePeriodSeconds: 7
                gracefulShutdown:
                  enabled: true
                  sleepTimeSeconds: 5
                probes: true
                # the gateway-proxy pod is ready only when a Gateway (Envoy listener) is listening
                customReadinessProbe:
                  httpGet:
                    scheme: HTTPS
                    port: 8443
                    path: /envoy-hc
                  failureThreshold: 2
                  initialDelaySeconds: 5
                  periodSeconds: 5
        gloo-fed:
          enabled: false
          create_license_secret: false
          glooFedApiserver:
            enable: false
        # set extauth requestTimeout to 1s for okta OIDC workflow
        global:
          extensions:
            extAuth:
              requestTimeout: 5s
            rateLimit:
              deployment:
                stats:
                  enabled: true
                    #repoURL: http://storage.googleapis.com/gloo-ee-test-helm
                    #targetRevision: 1.16.0-beta2-bfix-readiness-probe-45568b4
    repoURL: http://storage.googleapis.com/gloo-ee-helm
    targetRevision: 1.15.6
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
