# secrets must be in each namespace
apiVersion: v1
kind: Secret
metadata:
  name:  okta-client-secret
  namespace: gloo-mesh
type: extauth.solo.io/oauth
data:
  client-secret: X01TOVBKNTJOcFVKbzhIajJuRTR6ajkwaFg0QkZrVzYxU2RhWEpmRQ==